### ISSUE TITLE
Could ChimeraDatabase be serializable?

### ISSUE THREAD

**Issue by ericxsun** [SocialIntelligence/Chimera4j#1]
even when I defined my class with implementation of serialize like the following, `io.carpe.hyperscan.db.ChimeraDatabase` was still not serializable.

```java

public class JHyperScan implements Serializable {
  private ChimeraDatabase db;  // ChimeraDatabase is Un-Serializable
  private Scanner scanner = new Scanner();
  private LinkedList<ChimeraExpression> expressions = new LinkedList<>();

  public void add(List<Pair<String, EnumSet<ChimeraExpressionFlag>>> exps, Boolean clear) {
    if (clear) { expressions.clear(); }
    for (Pair<String, EnumSet<ChimeraExpressionFlag>> exp: exps) {
      expressions.add(new ChimeraExpression(exp.getLeft(), exp.getRight()));
    }
  }

  public void build() throws HyperscanException {
    db = ChimeraDatabase.compile(expressions);
    scanner.allocScratch(db);
  }

  public List<Match> parse(String doc) throws HyperscanException {
    return scanner.scan(db, doc);
  }

  public void release() throws HyperscanException {
    expressions.clear();
    scanner.close();
    db.close();
  }

  private void writeObject(ObjectOutputStream oos) throws IOException {
    Kryo kryo = new Kryo();
    kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

    kryo.register(ChimeraDatabase.class);
    kryo.register(Scanner.class);
    kryo.register(expressions.getClass());

    Output output = new Output(oos);
    kryo.writeObject(output, db);
    kryo.writeObject(output, scanner);
    kryo.writeObject(output, expressions);
    output.close();
  }


  @SuppressWarnings("unchecked")
  private void readObject(ObjectInputStream ois) throws IOException, ClassNotFoundException {
    Kryo kryo = new Kryo();
    kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

    Input input = new Input(ois);
    db = kryo.readObject(input, ChimeraDatabase.class);
    scanner = kryo.readObject(input, Scanner.class);
    expressions = (LinkedList<ChimeraExpression>) kryo.readObject(input, expressions.getClass());
    input.close();
  }
}
```

I have no ideas to serialize ChimeraDatabase,  could you give me any help? Thanks very much.

**Comment by SwiftEngineer** [comment]
@ericxsun sorry for the insanely late reply. The company that I work for (who owns this repo) has moved to a new organization. This project was left behind and notifications I'd stopped getting notifications for it.

To answer your question: Making the ChimeraDB serializable would be really difficult, if not impossible. The reason is that, at it's core, all it is is a connection to the hyperscan/chimera process that runs on your machine, outside the JVM. So even if you did make the ChimeraDB serializable, you're still going to have to figure out how to insure that the Chimera/Hyperscan process running natively on your machine is also serialized (or, at the very least get it to faithfully be recreated lazily).

If you haven't already solved this problem: my advice to you would be to figure out a way to avoid serializing the ChimeraDB. I suggest running Regexes in a batch compute, with a tool like AWS Batch or  Hashicorp's Nomad. 

If, on the off chance, you actually managed to get the ChimeraDB's working as a Serializable, please reach out! I'd love to see your solution!

**Comment by ericxsun** [comment]
@SwiftEngineer Thanks very much for your reply.  Right, to serialize ChimeraDB was really difficult. I finally figure out another way without serialize ChimeraDB but rebuild it: 
- serialize: save the expressions used to build db(ChimeraDB) and scanner(Scanner)
- deserialize: read the expressions and rebuild db and scanner

**Comment by SwiftEngineer** [comment]
Nice! Glad you found a solution
